#define LOGDIR		"F:\\radius\\radius-dist\\log\\radius"
#define RADDBDIR	"F:\\radius\\radius-dist\\raddb"
#define RUNDIR		"F:\\radius\\radius-dist\\run"
#define SBINDIR		"F:\\radius\\radius-dist\\sbin"
#define RADIR		"F:\\radius\\radius-dist\\log\\radius\\radacct"
